# Generated by Django 2.1 on 2019-02-25 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='city',
        ),
        migrations.AlterField(
            model_name='events',
            name='location',
            field=models.CharField(max_length=40),
        ),
    ]
