# Generated by Django 2.1 on 2019-02-25 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_events_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
