# Generated by Django 2.1 on 2019-02-25 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20190225_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='datetime',
            field=models.DateTimeField(blank=True),
        ),
    ]
