# Generated by Django 2.1 on 2019-02-25 21:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20190225_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedevent',
            name='seats',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2000)]),
        ),
    ]
