# Generated by Django 2.1 on 2019-02-26 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_bookedevent_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedevent',
            name='seats',
            field=models.CharField(max_length=20),
        ),
    ]
