# Generated by Django 2.1 on 2019-02-26 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20190226_0615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookedevent',
            name='seats',
        ),
        migrations.AlterField(
            model_name='bookedevent',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titleseats', to='events.Events'),
        ),
    ]
