# Generated by Django 2.1 on 2019-02-26 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_auto_20190226_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='datetime',
            field=models.DateTimeField(),
        ),
    ]
