# Generated by Django 2.1 on 2019-02-28 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_auto_20190228_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='pretty_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
